# Generated by Django 3.1.3 on 2020-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201126_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typeQuestion',
            field=models.IntegerField(choices=[(1, 'Radio'), (2, 'Checkbox')], default=1),
        ),
    ]
