# Generated by Django 3.1.3 on 2020-11-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_typequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rightFlg',
            field=models.BooleanField(default=True, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='timer',
            field=models.IntegerField(default=1, verbose_name='Время ответа на вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='typeQuestion',
            field=models.IntegerField(choices=[(1, 'Radio'), (2, 'Checkbox')], default=1, verbose_name='Тип вопроса'),
        ),
    ]
