# Generated by Django 3.1.3 on 2020-11-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201128_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninpoll',
            name='timer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rightFlg',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='polls',
            field=models.ManyToManyField(related_name='polls', through='polls.QuestionInPoll', to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='question',
            name='timer',
            field=models.IntegerField(verbose_name='Время ответа на вопрос (в секундах)'),
        ),
    ]
