# Generated by Django 3.1.3 on 2020-11-29 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201128_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='publicationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='questioninpoll',
            name='score',
            field=models.SmallIntegerField(null=True, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='questioninpoll',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='questioninpoll',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.question', verbose_name='Вопрос'),
        ),
    ]
