# Generated by Django 3.1.3 on 2020-12-03 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_auto_20201129_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer', verbose_name='Ответ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос из опроса')),
                ('questionPoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questioninpoll', verbose_name='Вопрос из опроса')),
            ],
        ),
    ]
