# Generated by Django 3.1.3 on 2020-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_answeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='score',
            field=models.SmallIntegerField(null=True, verbose_name='Количество баллов'),
        ),
    ]
