# Generated by Django 3.1.3 on 2020-12-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_answeruser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeruser',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос'),
        ),
    ]
