# Generated by Django 3.1.3 on 2020-12-07 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20201206_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
