# Generated by Django 3.1.3 on 2020-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_answerpoll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['textAnswer'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='answerpoll',
            options={'verbose_name': 'Ответ в опросах', 'verbose_name_plural': 'Ответы в опросах'},
        ),
        migrations.AlterModelOptions(
            name='answeruser',
            options={'ordering': ['owner'], 'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['publicationDate'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questioninpoll',
            options={'verbose_name': 'Связь вопроса и опроса', 'verbose_name_plural': 'Связь вопросов с опросами'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rightFlg',
        ),
    ]
