# Generated by Django 3.1.3 on 2020-12-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201213_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-16 20:04:01', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='update_dttm',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
