# Generated by Django 3.1.3 on 2020-12-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201219_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerpoll',
            options={'ordering': ['poll'], 'verbose_name': 'Ответ в опросах', 'verbose_name_plural': 'Ответы в опросах'},
        ),
    ]
